baseUrl: https://deprecatedapis.tts.quest/v2/voicevox/audio/
apiKey: u214197-710930L
speaker: 0
pitch: 0
intonationScale: 1
speed: 1
command: "#vv"
# 中文转换配置
chineseConvert:
  addSpaces: false  # 是否在转换后的片假名之间添加空格
